### PR TITLE
Fixes getInitialProps

### LINKED ISSUE #55: NextJS App getInitialProps
For some reason, getInitialProps in keycloak/nextjs isnt running at all when I wrap the app with appWIthKeycloak

I think it needs to pass it inside?

### PR DESCRIPTION
**Pull request by webdeb**
## Description

Fixes #55

### CODE REVIEW

**Comment by panz3r** [comment]
Hi @webdeb ,

Thanks for your contribution but I don't think this is the right solution, what happens if the first component inside `App` (so a single page) actually defines a `getInitialProps`? does that gets called after applying your suggested changes?

At the moment I'm evaluating rewriting the whole NextJS integration to be like the `razzle` one since recent changes introduced with `NextJS` 9.3 might bring more issues similar to #55 (specifically the introduction of `getStaticProps` and `getServerSideProps` methods which at the moment are ignored when an `App` is wrapped inside `appWithKeycloak`).

The best solution I can think of is to migrate away from `appWithKeycloak` and instead provide a smarter `SSRKeycloakProvider` component.
Hopefully I might be able to work on this in the coming days.

**Comment by webdeb** [comment]
> what happens if the first component inside App (so a single page) actually defines a getInitialProps? does that gets called after applying your suggested changes?

yes, thats the Point, it has to be called with the whole appContext param, you basically have to pass that through in order to *not change* the original parameter of `getInitialProps`

Inside `getInitialProps` by default Next uses will use its own App.getInitialProps where App comes from next/app.

I copied the whole nextjs/src to my project, made that change and its working properly on 9.3.
However, I think, your idea will make the code a bit simpler, since you can just import a proper Provider and the withKeycloak part will be only used to populate the props. 👍 

Its also how withApollo is handling it on the App level "next-with-apollo".

In my case I have, I need that non pageProps which are `passed-through` props from apollo:
```
export default withApollo(
  appWithKeycloak(keycloakSettings, {
    initConfig: {
      onLoad: "check-sso",
      promiseType: "native",
      checkLoginIframe: true,
    },
  })($App)
)

```

**Comment by webdeb** [comment]
@panz3r but I actually haven't tested it with any other setting, so I might be wrong

**Comment by panz3r** [comment]
No longer required.

See #55 for more details.

**Pull request closed without merging**
